[tool.isort]
profile = "black"

[tool.black]
line-length = 120

[tool.poetry]
name = "vaultops"
version = "3.1.7"
description = "Install Hashicorp Vault"
authors = ["arpan <arpan.rec@gmail.com>"]
license = "GLWTS"
readme = "README.md"
package-mode = true
packages = [{ include = "vaultops", from = "pylib" }]
scripts = { "vaultops" = "vaultops.__main__:main" }

[tool.poetry.dependencies]
python = "^3.10"
ansible = "10.2.0"
jmespath = "1.0.1"
pydantic = "2.8.2"
pydantic-settings = "2.4.0"
hvac = "2.3.0"
prettytable = "3.10.2"
bcrypt = "4.2.0"
python-terraform = "0.10.1"
pygithub = "2.3.0"
python-gnupg = "0.5.2"
boto3 = "1.34.152"
botocore = "1.34.152"
bitwarden-sdk = "0.1.0"
boto3-stubs = { extras = ["s3"], version = "1.34.152" }
# boto3-stubs = { extras = ["all"], version = "1.34.140" } 
s4cmd = "2.1.0"
lxml = "5.2.2"
pykeepass = "4.1.0.post1"
mypy = "1.11.1"
pylint = "3.2.6"
ansible-lint = { version = "24.7.0", markers = 'platform_system != "Windows"' }
poetry-plugin-export = "1.8.0"
detect-secrets = "1.5.0"
types-pyyaml = "6.0.12.20240724"
types-requests = "2.32.0.20240712"
types-jmespath = "1.0.2.20240106"
ansible-dev-tools = "24.7.2"
pyright = "1.1.374"
isort = "5.13.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
