[tool.isort]
profile = "black"

[tool.black]
line-length = 120

[tool.poetry]
name = "vaultops"
version = "3.1.0"
description = "Install Hashicorp Vault"
authors = ["arpan <arpan.rec@gmail.com>"]
license = "GLWTS"
readme = "README.md"
package-mode = true
packages = [{ include = "vaultops", from = "pylib" }]
scripts = { "vaultops" = "vaultops.__main__:main" }

[tool.poetry.dependencies]
python = "^3.10"
ansible = "10.1.0"
jmespath = "1.0.1"
pydantic = "2.8.2"
pydantic-settings = "2.3.4"
hvac = "2.3.0"
prettytable = "3.10.0"
bcrypt = "4.1.3"
python-terraform = "0.10.1"
pygithub = "2.3.0"
python-gnupg = "0.5.2"
boto3 = "1.34.141"
bitwarden-sdk = "0.1.0"
boto3-stubs = {extras = ["s3"], version = "1.34.141"}
# boto3-stubs = { extras = ["all"], version = "1.34.140" } 
s4cmd = "2.1.0"

[tool.poetry.group.dev.dependencies]
mypy = "1.10.1"
pylint = "3.2.5"
ansible-lint = { version = "24.6.1", markers = 'platform_system != "Windows"' }
poetry-plugin-export = "1.8.0"
detect-secrets = "1.5.0"
types-pyyaml = "6.0.12.20240311"
types-requests = "2.32.0.20240622"
types-jmespath = "1.0.2.20240106"
ansible-dev-tools = "24.6.1"
pyright = "1.1.370"
isort = "5.13.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
