[tool.black]
line-length = 120

[tool.poetry]
name = "vaultops"
version = "1.15.3"
description = "Install Hashicorp Vault"
authors = ["arpan <arpan.rec@gmail.com>"]
license = "GLWTS"
readme = "README.md"
package-mode = true
packages = [{ include = "vaultops", from = "pylib" }]
scripts = { "vaultops" = "vaultops.__main__:main" }

[tool.poetry.dependencies]
python = "^3.10"
ansible = "9.5.1"
jmespath = "1.0.1"
pydantic = "2.7.1"
pydantic-settings = "2.2.1"
hvac = "2.2.0"
prettytable = "3.10.0"
bcrypt = "4.1.3"
python-terraform = "0.10.1"
pygithub = "2.3.0"
python-gnupg = "^0.5.2"

[tool.poetry.group.dev.dependencies]
mypy = "1.10.0"
pylint = "3.2.0"
ansible-lint = { version = "24.5.0", markers = 'platform_system != "Windows"' }
poetry-plugin-export = "1.8.0"
detect-secrets = "1.5.0"
types-pyyaml = "6.0.12.20240311"
types-requests = "2.31.0.20240406"
types-jmespath = "1.0.2.20240106"
ansible-dev-tools = "24.5.0"
pyright = "1.1.363"
isort = "^5.13.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
