[tool.isort]
profile = "black"
line_length = 120

[tool.black]
line-length = 120

[tool.poetry]
name = "vaultops"
version = "1.1.2"
description = "Install Hashicorp Vault"
authors = ["arpan <arpan.rec@gmail.com>"]
license = "GLWTS"
readme = "README.md"
package-mode = true
packages = [{ include = "vaultops", from = "pylib" }]
scripts = { "vaultops" = "vaultops.__main__:main" }

[tool.poetry.dependencies]
python = "^3.10"
ansible = "10.2.0"
cryptography = "43.0.0"
jmespath = "1.0.1"
pydantic = "2.8.2"
pydantic-settings = "2.4.0"
hvac = "2.3.0"
prettytable = "3.11.0"
bcrypt = "4.2.0"
python-terraform = "0.10.1"
pygithub = "2.3.0"
python-gnupg = "0.5.2"
boto3 = "1.34.158"
boto3-stubs = { extras = ["s3"], version = "1.34.158" } # extras = ["all"]
mypy = "1.11.1"
pylint = "3.2.6"
ansible-lint = { version = "24.7.0", markers = 'platform_system != "Windows"' }
poetry-plugin-export = "1.8.0"
detect-secrets = "1.5.0"
types-pyyaml = "6.0.12.20240808"
types-requests = "2.32.0.20240712"
types-jmespath = "1.0.2.20240106"
ansible-dev-tools = "24.7.2"
pyright = "1.1.375"
isort = "5.13.2"
bandit = { extras = ["toml"], version = "1.7.9" }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
