---
name: "Bandit: A security linter from PyCQA"

"on":
    push:
        paths:
            - "**.py"
            - ".github/workflows/bandit.yml"
            - "poetry.lock"
            - "pyproject.toml"
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    bandit:
        runs-on: ubuntu-latest
        name: bandit
        strategy:
            fail-fast: false
            matrix:
                python-version: ["3.10", "3.11", "3.12", "3.13"]
        steps:
            - name: Checkout
              uses: actions/checkout@v4.2.2

            - name: Install poetry 1.8.4
              run: pipx install poetry==1.8.4

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v5.3.0
              with:
                  python-version: "${{ matrix.python-version }}"
                  cache: "poetry"
                  # cache-dependency-path: pyproject.toml

            - name: Install dependencies
              run: poetry install --with dev

            - name: Analysing the code with bandit
              run: poetry run bandit -r $(git ls-files '*.py')
