---
name: Linting

on: # yamllint disable-line rule:truthy
    push:
    workflow_dispatch:
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    linting:
        runs-on: ubuntu-latest
        name: Linting
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Python "3.10"
              uses: actions/setup-python@v5
              with:
                  python-version: "3.10"
                  cache: pip
                  cache-dependency-path: .github/files/requirements.txt

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3

            - name: Cache ansible
              uses: actions/cache@v4
              with:
                  path: |
                      ~/.ansible
                      ~/.cache/ansible-*
                  key: ansible-cache-${{ hashFiles('**/requirements.yml') }}

            - name: Install dependencies
              run: |-
                  set -ex
                  python -m pip install -r .github/files/requirements.txt
                  poetry config virtualenvs.create false --local
                  poetry install
                  ansible-galaxy install -r requirements.yml

            - name: Analysing the code with pylint
              run: |+
                  set -ex
                  pylint $(git ls-files '*.py')

            - name: Analysing the code with black
              run: |+
                  set -ex
                  black --check $(git ls-files '*.py')

            - name: Analysing the code with mypy
              run: |+
                  set -ex
                  mypy $(git ls-files '*.py') --check-untyped-defs

            - name: Analysing the code with yamllint
              run: |+
                  set -ex
                  yamllint .

            - name: Analysing the code with ansible-lint
              run: |+
                  set -ex
                  ansible-lint

            - name: Analysing the code with terraform
              run: |
                  set -ex
                  terraform fmt -check=true -recursive
