---
name: scans
"on":
    pull_request:
    push:
    workflow_dispatch:
    schedule:
        - cron: "0 4 * * *" # run once a day at 4 AM
jobs:
    gitleaks:
        name: gitleaks
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - uses: gitleaks/gitleaks-action@v2
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_BOT_API_TOKEN }}

    bandit:
        runs-on: ubuntu-latest
        name: bandit
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Python "3.10"
              uses: actions/setup-python@v5
              with:
                  python-version: "3.10"
                  cache: pip
                  cache-dependency-path: .github/files/requirements.txt

            - name: Install dependencies
              run: |-
                  set -ex
                  python -m pip install -r .github/files/requirements.txt
                  poetry config virtualenvs.create false --local
                  poetry install

            - name: Analysing the code with bandit
              run: |+
                  set -ex
                  bandit -r $(git ls-files '*.py')
