---
name: Terraform Linting
"on":
    push:
        paths:
            - "**.tf"
            - ".github/workflows/terraform-fmt.yml"
            - "codifiedvault/**"
    workflow_dispatch:
    pull_request:
        paths:
            - "**.tf"
            - ".github/workflows/terraform-fmt.yml"
            - "codifiedvault/**"

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    terraform-fmt:
        runs-on: ubuntu-latest
        name: terraform-fmt
        steps:
            - name: Checkout
              uses: actions/checkout@v4.2.2

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3.1.2

            - name: Analysing the code with terraform
              run: terraform fmt -check=true -recursive
